version: "3"
services:
  pgprovider:
    build: ./provider
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf
    ports:
      - 5432:5432

  pgsubscriber:
    build: ./subscriber
    depends_on:
      - "pgprovider"
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf
    ports:
      - 5433:5432

  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  pgexporter:
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:s3cr3t@pgprovider:5432/pg_logical_replication?sslmode=disable,postgresql://postgres:s3cr3t@pgsubscriber:5432/pg_logical_replication_results?sslmode=disable
      - PG_EXPORTER_DISABLE_SETTINGS_METRICS=true
      - PG_EXPORTER_EXTEND_QUERY_PATH=/config/queries.yaml
    image: wrouesnel/postgres_exporter
    volumes:
      - ./pgexporter/queries.yml:/config/queries.yaml
    ports:
      - 9187:9187
    depends_on:
      - pgprovider
      - pgsubscriber

  grafana:
    image: grafana/grafana:8.1.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=s3cr3t
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
